services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    environment:
      - "POSTGRES_DB=accounts"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
    ports:
      - "6432:5432"
  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: 'rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      - "15672:15672"
      - "5672:5672"
